### ISSUE TITLE
build: release does not post-release properly

### ISSUE THREAD

**Issue by Strazz1337** [zonneplan/open-telemetry-js#41]
The following steps in the release CI do not function properly after syncing all dependencies to the same version:

**Todo**

- [x] The new tag should be pushed.
- [x] The changelog should automatically be updated
- [x] The updated `package.json` versions should be pushed.

**Comment by Strazz1337** [comment]
#1440403e61fa975814173b3ac670064811f7bf5f
